### ISSUE TITLE
Y axis rendering reversed in 2D plots

### ISSUE THREAD

**Issue by ckjo** [MOEAFramework/J3#7]
As shown in the screenshot below, y axis scale values in 2D plots are always being rendered reversed. 
You can confirm this problem by selecting a specific spot and compare their y values between 2D and 3D plots.
Note that y axis renderings of 3D and parallel plots are working correctly. Only 2D plot has this issue.

![AAA](https://github.com/Project-Platypus/J3/assets/7942035/8af4c3f6-3954-4b03-8b38-6d577e1b6b48)

Dataset: [GAA_pset.csv](https://github.com/Project-Platypus/J3/files/13310749/GAA_pset.csv)

**Comment by dhadka** [comment]
Fixed in 2.0.0.
